import sqlite3

con = sqlite3.connect("brioche.db")

con.execute("CREATE TABLE USUARIOS( 	IDUSUARIO INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE VARCHAR(128) NOT NULL,CONTRASENA VARCHAR(64) NOT NULL,CORREO VARCHAR(32) NOT NULL,ROL VARHCAR(16) NOT NULL,ESTADO VARCHAR(16) NOT NULL)")

print("Tabla usuarios creada exitosamente")

con.execute("CREATE TABLE VENTA(FACTURA INT PRIMARY KEY,FECHA DATE NOT NULL,IDUSUARIO INT NOT NULL,VALOR INT NOT NULL,FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO))")

print("Tabla venta creada exitosamente")

con.execute("CREATE TABLE PRODUCTO(IDPRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE VARCHAR(128) NOT NULL,CANTIDAD INT,PRECIO_UNITARIO INT,IMAGEN VARCHAR(512) NOT NULL)")

print("Tabla producto creada exitosamente")

con.close()
